### ISSUE TITLE
Add tags to blog posts

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary.fund#349]
I propose to add tags to blog posts to make them more general. 

Proposals:
- `quarterly updates`
- `mitiq`
- `metriq`
- `research`
- `guest post`
- possible proposal: add author name as tags. So that if you choose `UF team` or `will zeng` you find related posts. Any other suggestions @willzeng @natestemen @andreamari @Misty-W ?

**Comment by natestemen** [comment]
I like the idea of `quarterly update`, `mitiq`, `metriq`, `research`. `guest post` seems a bit odd to me. I don't see too many people wanting to only look at guest posts, but not opposed to it.

I also like the idea of adding `event` and `community` for events, and things related to community building respectively.

Instead of using tags to track authorship in addition to having the `author` attribute attached to each post, is it possible to use the data directly from the `author` attribute?

**Comment by willzeng** [comment]
Would propose that most people find things by search and not by tag. We can prioritize focus elsewhere and reopen later if needed
