### ISSUE TITLE
Build failing on deploy CI / website

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitary.fund#374]
This commit https://github.com/unitaryfund/unitary.fund/commit/5eb76635df33962fb12933bd84aedea37847a21b made CI's deployment fail and the update does not show up on the site. Any idea of why? It's literally just a line of text in a `.mdx` file. Are those file protected? Cc @joshdavenport @WrathfulSpatula.

**Comment by WrathfulSpatula** [comment]
We've altered that file in the past, I'm pretty sure, so it's not "protected." Looking at the commit, there's no reason I can discern this should have happened. (This commit might not have been the cause of the CI failure, or the CI might have failed more-or-less at random.)

**Comment by joshdavenport** [comment]
No issue with changing this file, nothing is protected theoretically but just best to not touch files or parts of files that you don't understand what it's doing.

Interestingly the build here was totally fine, it was the deployment to GitHub Pages itself that actually failed as it timed out after 10 minutes. That's very odd, and the action output doesn't indicate why it ended up taking so long. Short bit of research indicates that this often happens if the final build artefact is too large to upload in that time, but it was only 30mb which shouldn't be anywhere close to too big.

Anyway, I'm 99% sure it was a blip as I just pushed a menial change to README.md and all was good. Kinda strange as there were [no issues reported yesterday](https://www.githubstatus.com/history).

**Comment by nathanshammah** [comment]
Thanks @joshdavenport and @WrathfulSpatula. I did try rerun the deploy, but without a new commit, the CI failed. Regarding this:
> best to not touch files or parts of files that you don't understand what it's doing.
My impression is that it is fine to edit `.mdx` files that contain text even without knowing much about the astro build. Hope that's fine for the future too.
