### ISSUE TITLE
update /ideas page

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/unitary.fund#619]
The [microgrant ideas page](https://unitary.fund/ideas/) is quite out of date. It would be great to update it with new ideas from the grant review board. So there are two steps to resolving this

1. Reaching out to the right people to collect project ideas
2. updating the [code](https://github.com/unitaryfund/unitary.fund/blob/a26bbe69cad1343a4ade85741d39c773cac55ee6/src/pages/ideas.mdx)

**Comment by KallieFerguson** [comment]
@natestemen Rather than collecting a new list that should be regularly maintained and updated and may frequently shift depending on the make up of the current board and new QC developments, my opinion is that we should actually point people to the grant page for inspiration. This will allow people to see 1) What types of projects are being championed recently and 2) Gives additional exposure to the micrograntees, with people looking at live projects that may interest them or that they might want to help get involved in.

**Comment by jordandsullivan** [comment]
@KallieFerguson I agree, getting an idea of recently acquired grants is good. Though I wonder if for instance we want to solicit more projects in an area we haven't yet seen and applications, what would be an alternate way to do that?

**Comment by KallieFerguson** [comment]
@jordandsullivan I will request feedback on whether there are specific project ideas we want to see more of. My guess is that we don't want to see a ton of new applications in any particular area over a sustained period of time, and this may be better suited to an occasional social media post encouraging people to apply, especially if they have an idea in XYZ area. We could make this a part of the regular monthly agenda where we kick it off with a quick check-in with advisors about project ideas they'd like to see.

**Comment by willzeng** [comment]
I agree with Kallie's points. Not having the page reduces the maintenance
burden. It originally was added when we had many less examples of projects.

Would propose that we remove the project ideas page entirely.

*Will Zeng*
President
*Unitary Fund - because evolution is unitary*

Unitary Fund <https://unitary.fund/> | Linkedin
<https://www.linkedin.com/company/unitary-fund/> | X
<https://x.com/home?lang=en> | Discord
<https://discord.com/invite/unitary-fund-764231928676089909>
